version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
networks:
  frontend:
    name: nodedocker
  backend:
    name: nodedocker