version: "3"

services:
  frontend:
    image: frontend:1.0
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rede

  backend:
    image: backend:1.0
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - rede
networks:
  rede:
    driver: bridge